/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Rindo compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLRindoElement, JSXBase } from "@rindo/core/internal";
export namespace Components {
    interface MyApp {
        "offset": number;
    }
    interface MyItem {
        "index": number;
    }
    interface MyList {
        "offset": number;
    }
}
declare global {
    interface HTMLMyAppElement extends Components.MyApp, HTMLRindoElement {
    }
    var HTMLMyAppElement: {
        prototype: HTMLMyAppElement;
        new (): HTMLMyAppElement;
    };
    interface HTMLMyItemElement extends Components.MyItem, HTMLRindoElement {
    }
    var HTMLMyItemElement: {
        prototype: HTMLMyItemElement;
        new (): HTMLMyItemElement;
    };
    interface HTMLMyListElement extends Components.MyList, HTMLRindoElement {
    }
    var HTMLMyListElement: {
        prototype: HTMLMyListElement;
        new (): HTMLMyListElement;
    };
    interface HTMLElementTagNameMap {
        "my-app": HTMLMyAppElement;
        "my-item": HTMLMyItemElement;
        "my-list": HTMLMyListElement;
    }
}
declare namespace LocalJSX {
    interface MyApp {
        "offset"?: number;
    }
    interface MyItem {
        "index"?: number;
    }
    interface MyList {
        "offset"?: number;
    }
    interface IntrinsicElements {
        "my-app": MyApp;
        "my-item": MyItem;
        "my-list": MyList;
    }
}
export { LocalJSX as JSX };
declare module "@rindo/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-app": LocalJSX.MyApp & JSXBase.HTMLAttributes<HTMLMyAppElement>;
            "my-item": LocalJSX.MyItem & JSXBase.HTMLAttributes<HTMLMyItemElement>;
            "my-list": LocalJSX.MyList & JSXBase.HTMLAttributes<HTMLMyListElement>;
        }
    }
}
