/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Rindo compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLRindoElement, JSXBase } from "@rindo/core/internal";
export namespace Components {
    interface HelloWorld {
    }
}
declare global {
    interface HTMLHelloWorldElement extends Components.HelloWorld, HTMLRindoElement {
    }
    var HTMLHelloWorldElement: {
        prototype: HTMLHelloWorldElement;
        new (): HTMLHelloWorldElement;
    };
    interface HTMLElementTagNameMap {
        "hello-world": HTMLHelloWorldElement;
    }
}
declare namespace LocalJSX {
    interface HelloWorld {
    }
    interface IntrinsicElements {
        "hello-world": HelloWorld;
    }
}
export { LocalJSX as JSX };
declare module "@rindo/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "hello-world": LocalJSX.HelloWorld & JSXBase.HTMLAttributes<HTMLHelloWorldElement>;
        }
    }
}
