export const RINDO_CORE_ID = '@rindo/core';
export const RINDO_INTERNAL_ID = '@rindo/core/internal';
export const RINDO_APP_DATA_ID = '@rindo/core/internal/app-data';
export const RINDO_APP_GLOBALS_ID = '@rindo/core/internal/app-globals';
export const RINDO_HYDRATE_FACTORY_ID = '@rindo/core/hydrate-factory';
export const RINDO_INTERNAL_CLIENT_ID = '@rindo/core/internal/client';
export const RINDO_INTERNAL_CLIENT_PATCH_ID = '@rindo/core/internal/client/patch';
export const RINDO_INTERNAL_HYDRATE_ID = '@rindo/core/internal/hydrate';
export const RINDO_MOCK_DOC_ID = '@rindo/core/mock-doc';
export const APP_DATA_CONDITIONAL = '?app-data=conditional';
export const LAZY_BROWSER_ENTRY_ID = '@lazy-browser-entrypoint' + APP_DATA_CONDITIONAL;
export const LAZY_EXTERNAL_ENTRY_ID = '@lazy-external-entrypoint' + APP_DATA_CONDITIONAL;
export const USER_INDEX_ENTRY_ID = '@user-index-entrypoint';
