/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Rindo compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLRindoElement, JSXBase } from "@rindo/core/internal";
export namespace Components {
    interface HelloVdom {
    }
}
declare global {
    interface HTMLHelloVdomElement extends Components.HelloVdom, HTMLRindoElement {
    }
    var HTMLHelloVdomElement: {
        prototype: HTMLHelloVdomElement;
        new (): HTMLHelloVdomElement;
    };
    interface HTMLElementTagNameMap {
        "hello-vdom": HTMLHelloVdomElement;
    }
}
declare namespace LocalJSX {
    interface HelloVdom {
    }
    interface IntrinsicElements {
        "hello-vdom": HelloVdom;
    }
}
export { LocalJSX as JSX };
declare module "@rindo/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "hello-vdom": LocalJSX.HelloVdom & JSXBase.HTMLAttributes<HTMLHelloVdomElement>;
        }
    }
}
