name: 'Rindo Weekly Release'

on:
  schedule:
    # Run every Sunday at 11:00 PM (UTC) (https://crontab.guru/#00_23_*_*_sun)
    # This is done to have a weekly build on Sunday ready for the Family Framework/Rindo Eval Workflow:
    # https://github.com/familyjs/family-framework/blob/main/.github/workflows/rindo-eval.yml
    - cron: '00 23 * * sun'
  workflow_dispatch:
    # Allow this workflow to be run on-demand

jobs:
  build_core:
    name: Build
    uses: ./.github/workflows/build.yml

  get-weekly-version:
    name: Get Weekly Build Version
    needs: [build_core]
    runs-on: ubuntu-22.04
    outputs:
      weekly-version: ${{ steps.get-weekly-version.outputs.WEEKLY_VERSION }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Get Core Dependencies
        uses: ./.github/workflows/actions/get-core-dependencies

      - name: Download Build Archive
        uses: ./.github/workflows/actions/download-archive
        with:
          name: rindo-core
          path: .
          filename: rindo-core-build.zip

      - name: Grant execution permissions
        run: chmod +x ./bin/rindo

      - name: Get Version
        id: get-weekly-version
        run: |
          # A unique string to publish Rindo under
          # e.g. "3.0.1-dev.1677185104.7c87e34"
          #
          # Note: A 'weekly' build is just a 'dev' build that is published at
          # weekend, under the 'weekly' tag in npm
          #
          # Pull this value from the compiled artifacts
          WEEKLY_VERSION=$(./bin/rindo version)

          echo "Using version $WEEKLY_VERSION"

          # store a key/value pair in GITHUB_OUTPUT
          # e.g. "WEEKLY_VERSION=3.0.1-dev.1677185104.7c87e34"
          echo "WEEKLY_VERSION=$WEEKLY_VERSION" >> $GITHUB_OUTPUT

        shell: bash

  release-rindo-weekly-build:
    name: Publish Weekly Build
    needs: [get-weekly-version, build_core]
    runs-on: ubuntu-22.04
    permissions:
      id-token: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - uses: ./.github/workflows/actions/publish-npm
        with:
          tag: weekly
          version: ${{ needs.get-weekly-version.outputs.weekly-version }}
          token: ${{ secrets.NPM_TOKEN }}
